### ISSUE TITLE
Extra support

### ISSUE THREAD

**Issue by aamaanaa** [charltoncr/ChaCha20#1]
hi first of all thanks

i wonder if support for longer key, iv lengths can be implemented?

also, can we add a SetCounter function to manually set the counter of the iv like the golang one does?

**Comment by charltoncr** [comment]
Longer key and iv lengths could be implemented I suppose, but I am not a cryptography specialist. Longer keys and ivs would require a substantial redesign of chacha20 that I am not competent to do or know how to test for correctness. I'm sure the original chacha20 designer verified that the current design is cryptographically safe. My only role was to port the C language implementation to golang.

The SetCounter method you request is already implemented in my golang port. Its name is Seek. I didn't document it at https://charltoncr.github.io/ChaCha20/, but if you inspect chacha20.go you will find it. Try running the 'go doc' command in ChaCha20 directory and you will get much detail that I did not include in ReadMe.md.

Ron Charlton ***@***.***>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The whole aim of practical politics is to keep the
populace alarmed (and hence clamorous
to be led to safety) by menacing it with an endless
series of hobgoblins, all of them imaginary.
  ― H. L. Mencken

**Comment by charltoncr** [comment]
Hello again. I changed chacha20's Seek method to be sure it works correctly on both big-endian and little-endian architectures. Please use the latest version of chacha20 that I uploaded a few minutes ago.


Ron Charlton ***@***.***>
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The whole aim of practical politics is to keep the
populace alarmed (and hence clamorous
to be led to safety) by menacing it with an endless
series of hobgoblins, all of them imaginary.
  ― H. L. Mencken
